//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filme.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Name="Primul serviciu webSoap", Namespace="Serviciu_web", ConfigurationName="ServiceReference1.PrimulserviciuwebSoap")]
    public interface PrimulserviciuwebSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace Serviciu_web is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="Serviciu_web/HelloWorld", ReplyAction="*")]
        Filme.ServiceReference1.HelloWorldResponse HelloWorld(Filme.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name link1 from namespace Serviciu_web is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="Serviciu_web/generateUrl", ReplyAction="*")]
        Filme.ServiceReference1.generateUrlResponse generateUrl(Filme.ServiceReference1.generateUrlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="Serviciu_web/add", ReplyAction="*")]
        double add(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="Serviciu_web/load", ReplyAction="*")]
        void load();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="Serviciu_web", Order=0)]
        public Filme.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Filme.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="Serviciu_web", Order=0)]
        public Filme.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Filme.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="Serviciu_web")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generateUrlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="generateUrl", Namespace="Serviciu_web", Order=0)]
        public Filme.ServiceReference1.generateUrlRequestBody Body;
        
        public generateUrlRequest() {
        }
        
        public generateUrlRequest(Filme.ServiceReference1.generateUrlRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="Serviciu_web")]
    public partial class generateUrlRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string link1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string link2;
        
        public generateUrlRequestBody() {
        }
        
        public generateUrlRequestBody(string link1, string link2) {
            this.link1 = link1;
            this.link2 = link2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generateUrlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="generateUrlResponse", Namespace="Serviciu_web", Order=0)]
        public Filme.ServiceReference1.generateUrlResponseBody Body;
        
        public generateUrlResponse() {
        }
        
        public generateUrlResponse(Filme.ServiceReference1.generateUrlResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="Serviciu_web")]
    public partial class generateUrlResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string generateUrlResult;
        
        public generateUrlResponseBody() {
        }
        
        public generateUrlResponseBody(string generateUrlResult) {
            this.generateUrlResult = generateUrlResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PrimulserviciuwebSoapChannel : Filme.ServiceReference1.PrimulserviciuwebSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PrimulserviciuwebSoapClient : System.ServiceModel.ClientBase<Filme.ServiceReference1.PrimulserviciuwebSoap>, Filme.ServiceReference1.PrimulserviciuwebSoap {
        
        public PrimulserviciuwebSoapClient() {
        }
        
        public PrimulserviciuwebSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PrimulserviciuwebSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrimulserviciuwebSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrimulserviciuwebSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Filme.ServiceReference1.HelloWorldResponse Filme.ServiceReference1.PrimulserviciuwebSoap.HelloWorld(Filme.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Filme.ServiceReference1.HelloWorldRequest inValue = new Filme.ServiceReference1.HelloWorldRequest();
            inValue.Body = new Filme.ServiceReference1.HelloWorldRequestBody();
            Filme.ServiceReference1.HelloWorldResponse retVal = ((Filme.ServiceReference1.PrimulserviciuwebSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Filme.ServiceReference1.generateUrlResponse Filme.ServiceReference1.PrimulserviciuwebSoap.generateUrl(Filme.ServiceReference1.generateUrlRequest request) {
            return base.Channel.generateUrl(request);
        }
        
        public string generateUrl(string link1, string link2) {
            Filme.ServiceReference1.generateUrlRequest inValue = new Filme.ServiceReference1.generateUrlRequest();
            inValue.Body = new Filme.ServiceReference1.generateUrlRequestBody();
            inValue.Body.link1 = link1;
            inValue.Body.link2 = link2;
            Filme.ServiceReference1.generateUrlResponse retVal = ((Filme.ServiceReference1.PrimulserviciuwebSoap)(this)).generateUrl(inValue);
            return retVal.Body.generateUrlResult;
        }
        
        public double add(double a, double b) {
            return base.Channel.add(a, b);
        }
        
        public void load() {
            base.Channel.load();
        }
    }
}
